### PR TITLE
Creating github pages

### PR DESCRIPTION
**Pull request by JohannesKarwou**
- [x] create a github page using sphinx
- [x] use github action to create the page

### CODE REVIEW

**Comment by JohannesKarwou** [comment]
There should be now a github page of this project on https://wiederm.github.io/endstate_correction/. If one wants to adapt the documentation one needs to modify the according ```rst``` file in the ```docs``` folder, if you want to create a new section add the name of the ```rst``` file into the toctree which can be seen in ```docs/index.rst``` :

```
.. toctree::
   :maxdepth: 2
   :caption: Contents:

   getting_started
   theory
   api
```
As soon as you change something in the ```docs``` folder, no matter on which branch, and commit this change, a github action will start and push stuff to the ```gh-pages``` branch, afterwards the page will build from this ```gh-pages``` branch (you don't need to do anything about it, just modifying the ```rst``` file everything else will be handled by the github actions).

Currently, the ```api``` documentation is not set up properly, I will look at this during the next day, but we can still start using the page...

**Comment by JohannesKarwou** [comment]
API documentation is working now as well!

**Comment by wiederm** [comment]
Awesome! API documentation is super great! I see that I have some documenting to do :-)

**Review by wiederm — APPROVED** [review]
this is great! Thanks

**Pull request merged**
