### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by wiederm**
## Description
Streamlinging endstate correction functions

## Todos
 - [x]  remove openff functions
  - [x] move to dcd instead of pickle files
  - [x] provide convenience function to perform endstate corrections in a modular way for all three environments
 - [x]  update references to endstate_correction
 - [x] provide example scripts

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by wiederm** [comment]
I think this is ready for a review now! The CI problem will be moved to a separate PR, so please ignore test failures on GH for now, but they should pass locally of course.

**Review by JohannesKarwou — APPROVED** [review]
On my local machine and on the rs02 the sample input scripts run fine!
Looks all very good!

**Review by saratk1 — APPROVED** [review]
Looks very good, thanks!

**Comment by wiederm** [comment]
Thanks! Will merge!

**Pull request merged**
